[book]
authors = ["baerwang"]
language = "zh"
multilingual = false
src = "src"
title = "夜雨秋灯录"

[output.html]
site-url = "/mdbook/"
git-repository-url = "https://github.com/baerwang/mdbook"
edit-url-template = "https://github.com/baerwang/mdbook/edit/main/{path}"
mathjax-support = true
additional-css = ["docs/style.css"]
additional-js = ["docs/sidebar.js"]

[output.html.fold]
enable = false

[output.html.print]
enable = false