[book]
authors = ["baerwang"]
language = "zh"
multilingual = false
src = "src"
title = "notes"

[output.html]
site-url = "/mdbook/"
git-repository-url = "https://github.com/baerwang/mdbook"
edit-url-template = "https://github.com/baerwang/mdbook/edit/main/{path}"
mathjax-support = true
additional-js = ["docs/giscus.js"]

[output.html.fold]
enable = false

[output.html.print]
enable = false

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.playground]
editable = true